# Usar la imagen oficial de Elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:8.16.1

# Copia tu archivo de configuración desde el directorio local al contenedor
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Exponer el puerto por defecto de Elasticsearch
EXPOSE 9200

# Ejecutar Elasticsearch
CMD ["elasticsearch", "-E", "xpack.security.enabled=true", "-E", "xpack.security.authc.api_key.enabled=true"]