# Generated by Django 5.0.9 on 2024-10-04 16:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_initial'),
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resource_files.pointvectorlayerfile'),
        ),
    ]
