# Generated by Django 5.0.6 on 2024-06-17 02:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_initial'),
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='resource_files.pointvectorlayerfile'),
        ),
    ]
