# Generated by Django 5.0.9 on 2024-10-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometrycollection',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='linestring',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='multilinestring',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='multipoint',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='multipolygon',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='point',
            name='file_uuid',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='file_uuid',
        ),
        migrations.AddField(
            model_name='geometrycollection',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linestring',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multilinestring',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multipolygon',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
