# Generated by Django 5.0.6 on 2024-06-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_point_file'),
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-id'], 'verbose_name': 'Point', 'verbose_name_plural': 'Points'},
        ),
        migrations.AlterField(
            model_name='point',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='resource_files.pointvectorlayerfile'),
        ),
    ]
