# Generated by Django 5.0.9 on 2024-10-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_point_source_file'),
        ('resource_files', '0003_pointvectorlayerfile_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.pointvectorlayerfile'),
        ),
    ]
