# Generated by Django 5.0.6 on 2024-06-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_remove_point_file'),
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='resource_files.pointvectorlayerfile'),
        ),
    ]
