# Generated by Django 5.0.6 on 2024-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_point_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='file',
        ),
        migrations.AddField(
            model_name='point',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
