# Generated by Django 5.0.6 on 2024-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_remove_point_file_point_file_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='point',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='point',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='point',
            name='live',
        ),
        migrations.RemoveField(
            model_name='point',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='point',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='point',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='point',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
