# Generated by Django 5.0.6 on 2024-06-17 11:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_remove_point_expire_at_remove_point_expired_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrycollection',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='linestring',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='multilinestring',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='multipolygon',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='multipoint',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipoints', to='resources.multipointvectorlayer'),
        ),
    ]
