# Generated by Django 5.0.6 on 2024-06-15 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointVectorLayerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='resources/files/')),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Point Vector Layer File',
                'verbose_name_plural': 'Resource Files: Point Vector Layer Files',
            },
        ),
    ]
