# Generated by Django 5.0.6 on 2024-06-17 01:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource_files', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.pointvectorlayer'),
        ),
    ]
