# Generated by Django 5.0.9 on 2024-10-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorlayerfile',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
