# Generated by Django 5.0.6 on 2024-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='kind',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
