# Generated by Django 5.0.4 on 2024-04-22 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_initial'),
        ('resource_files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_files', to='resources.pointvectorlayer'),
        ),
    ]
