# Generated by Django 5.0.6 on 2024-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0003_alter_pointvectorlayerfile_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='kind',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
