# Generated by Django 5.0.6 on 2024-06-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0003_pointvectorlayerfile_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='live',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked_by',
        ),
    ]
