# Generated by Django 5.0.4 on 2024-04-22 01:55

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_initial'),
        ('resource_files', '0003_alter_pointvectorlayerfile_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_files', to='resources.pointvectorlayer'),
        ),
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
