# Generated by Django 5.0.9 on 2024-10-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0003_remove_pointvectorlayerfiledocument_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='uuid',
        ),
        migrations.AddField(
            model_name='pointvectorlayerfile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
