# Generated by Django 5.0.9 on 2024-10-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0004_alter_pointvectorlayerfile_layer'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.pointvectorlayer'),
        ),
    ]
