# Generated by Django 5.0.4 on 2024-04-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0004_alter_pointvectorlayerfile_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorlayerfile',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
