# Generated by Django 5.0.9 on 2024-10-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0004_remove_pointvectorlayerfile_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointvectorlayerfiledocument',
            options={'verbose_name': 'Point Vector Layer File Document', 'verbose_name_plural': 'Files: Point Vector Layer File Documents'},
        ),
    ]
