# Generated by Django 5.0.9 on 2024-10-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0005_alter_pointvectorlayerfiledocument_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointVectorLayerFile',
        ),
    ]
