# Generated by Django 5.0.4 on 2024-04-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0005_pointvectorlayerfile_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='pointvectorlayerfile',
            name='locked_by',
        ),
    ]
