# Generated by Django 5.0.9 on 2024-10-04 17:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0005_alter_pointvectorlayerfile_layer'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.pointvectorlayer'),
        ),
    ]
