# Generated by Django 5.0.6 on 2024-06-17 11:09

import django.db.models.deletion
import modelcluster.fields
import resource_files.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0006_remove_pointvectorlayerfile_expire_at_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='kind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_files', to='resources.pointvectorlayer'),
        ),
        migrations.CreateModel(
            name='LineStringVectorLayerFile',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
                ('kind', models.CharField(max_length=50, null=True)),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='linestring_files', to='resources.linestringvectorlayer')),
            ],
            options={
                'verbose_name': 'LineString Vector Layer File',
                'verbose_name_plural': 'Resource Files: LineString Vector Layer Files',
            },
        ),
        migrations.CreateModel(
            name='MultiLineStringVectorLayerFile',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
                ('kind', models.CharField(max_length=50, null=True)),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multilinestring_files', to='resources.linestringvectorlayer')),
            ],
            options={
                'verbose_name': 'MultiLineString Vector Layer File',
                'verbose_name_plural': 'Resource Files: MultiLineString Vector Layer Files',
            },
        ),
        migrations.CreateModel(
            name='MultiPointVectorLayerFile',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
                ('kind', models.CharField(max_length=50, null=True)),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipoint_files', to='resources.pointvectorlayer')),
            ],
            options={
                'verbose_name': 'MultiPoint Vector Layer File',
                'verbose_name_plural': 'Resource Files: MultiPoint Vector Layer Files',
            },
        ),
        migrations.CreateModel(
            name='MultiPolygonVectorLayerFile',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
                ('kind', models.CharField(max_length=50, null=True)),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipolygon_files', to='resources.linestringvectorlayer')),
            ],
            options={
                'verbose_name': 'MultiPolygon Vector Layer File',
                'verbose_name_plural': 'Resource Files: MultiPolygon Vector Layer Files',
            },
        ),
        migrations.CreateModel(
            name='PolygonVectorLayerFile',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
                ('kind', models.CharField(max_length=50, null=True)),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_files', to='resources.linestringvectorlayer')),
            ],
            options={
                'verbose_name': 'Polygon Vector Layer File',
                'verbose_name_plural': 'Resource Files: Polygon Vector Layer Files',
            },
        ),
    ]
