# Generated by Django 5.0.6 on 2024-06-16 17:45

import resource_files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0007_remove_pointvectorlayerfile_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file]),
        ),
    ]
