# Generated by Django 5.0.6 on 2024-06-17 11:19

import django.db.models.deletion
import modelcluster.fields
import resource_files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0007_alter_pointvectorlayerfile_kind_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestringvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_linestring_vector_file]),
        ),
        migrations.AlterField(
            model_name='multilinestringvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multilinestring_vector_file]),
        ),
        migrations.AlterField(
            model_name='multilinestringvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multilinestring_files', to='resources.multilinestringvectorlayer'),
        ),
        migrations.AlterField(
            model_name='multipointvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multipoint_vector_file]),
        ),
        migrations.AlterField(
            model_name='multipointvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipoint_files', to='resources.multipointvectorlayer'),
        ),
        migrations.AlterField(
            model_name='multipolygonvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multipolygon_vector_file]),
        ),
        migrations.AlterField(
            model_name='multipolygonvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipolygon_files', to='resources.multipolygonvectorlayer'),
        ),
        migrations.AlterField(
            model_name='polygonvectorlayerfile',
            name='file',
            field=models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_polygon_vector_file]),
        ),
        migrations.AlterField(
            model_name='polygonvectorlayerfile',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_files', to='resources.polygonvectorlayer'),
        ),
    ]
