# Generated by Django 5.0.4 on 2024-04-22 03:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0008_remove_pointvectorlayerfile_latest_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorlayerfile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointvectorlayerfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
