# Generated by Django 5.0.6 on 2024-06-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_files', '0008_alter_linestringvectorlayerfile_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linestringvectorlayerfile',
            options={'verbose_name': 'LineString Vector Layer File', 'verbose_name_plural': 'Files: LineString Vector Layer Files'},
        ),
        migrations.AlterModelOptions(
            name='multilinestringvectorlayerfile',
            options={'verbose_name': 'MultiLineString Vector Layer File', 'verbose_name_plural': 'Files: MultiLineString Vector Layer Files'},
        ),
        migrations.AlterModelOptions(
            name='multipointvectorlayerfile',
            options={'verbose_name': 'MultiPoint Vector Layer File', 'verbose_name_plural': 'Files: MultiPoint Vector Layer Files'},
        ),
        migrations.AlterModelOptions(
            name='multipolygonvectorlayerfile',
            options={'verbose_name': 'MultiPolygon Vector Layer File', 'verbose_name_plural': 'Files: MultiPolygon Vector Layer Files'},
        ),
        migrations.AlterModelOptions(
            name='pointvectorlayerfile',
            options={'verbose_name': 'Point Vector Layer File', 'verbose_name_plural': 'Files: Point Vector Layer Files'},
        ),
        migrations.AlterModelOptions(
            name='polygonvectorlayerfile',
            options={'verbose_name': 'Polygon Vector Layer File', 'verbose_name_plural': 'Files: Polygon Vector Layer Files'},
        ),
    ]
