# Generated by Django 5.0.6 on 2024-06-17 01:57

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import resources.models
import uuid
import wagtail.fields
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0001_initial'),
        ('resource_attrs', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('abstract', wagtail.fields.RichTextField(blank=True, null=True)),
                ('purpose', wagtail.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.URLField(blank=True, null=True)),
                ('other_constraints', wagtail.fields.RichTextField(blank=True, null=True)),
                ('supplemental_information', wagtail.fields.RichTextField(blank=True, null=True)),
                ('data_quality_statement', wagtail.fields.RichTextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_advertised', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('popular_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resource_attrs.resourcecategory', validators=[resources.models.is_resourcecategory_live])),
                ('date_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatadatetype')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatalanguage')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatalicense')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('maintenance_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatamaintenancefrequency')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('regions', models.ManyToManyField(blank=True, to='metadata.datasetmetadataregion')),
                ('restriction_code_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatarestrictioncodetype')),
                ('spatial_representation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadataspatialrepresentationtype')),
                ('topic_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatatopiccategory')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
            bases=(wagtail.models.WorkflowMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'Data Table',
                'verbose_name_plural': 'Data Tables',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='GeometryCollectionVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'GeometryCollection Vector Layer',
                'verbose_name_plural': 'GeometryCollection Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='LineStringVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'LineString Vector Layer',
                'verbose_name_plural': 'LineString Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='MultiLineStringVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'MultiLineString Vector Layer',
                'verbose_name_plural': 'MultiLineString Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='MultiPointVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'MultiPoint Vector Layer',
                'verbose_name_plural': 'MultiPoint Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='MultiPolygonVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'MultiPolygon Vector Layer',
                'verbose_name_plural': 'MultiPolygon Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='PointVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'Point Vector Layer',
                'verbose_name_plural': 'Resources: Point Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='PolygonVectorLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'Polygon Vector Layer',
                'verbose_name_plural': 'Polygon Vector Layers',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
            ],
            options={
                'verbose_name': 'Raster Layer',
                'verbose_name_plural': 'Raster Layers',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='RemoteWFS',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('service_type', models.CharField(choices=[('', 'Remote service type'), ('remote_wms', 'Remote WMS'), ('remote_wfs', 'Remote WFS'), ('remote_wcs', 'Remote WCS'), ('remote_csw', 'Remote CSW'), ('remote_generic_rest', 'Remote Generic RESTful API'), ('remote_arcgis_rest', 'Remote ArcGIS REST API')], default='wms', max_length=255)),
                ('service_url', models.URLField()),
            ],
            options={
                'verbose_name': 'WFS Service',
                'verbose_name_plural': 'WFS Services',
            },
            bases=('resources.resource', models.Model),
        ),
        migrations.CreateModel(
            name='RemoteWMS',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('service_type', models.CharField(choices=[('', 'Remote service type'), ('remote_wms', 'Remote WMS'), ('remote_wfs', 'Remote WFS'), ('remote_wcs', 'Remote WCS'), ('remote_csw', 'Remote CSW'), ('remote_generic_rest', 'Remote Generic RESTful API'), ('remote_arcgis_rest', 'Remote ArcGIS REST API')], default='wms', max_length=255)),
                ('service_url', models.URLField()),
            ],
            options={
                'verbose_name': 'WMS Service',
                'verbose_name_plural': 'WMS Services',
            },
            bases=('resources.resource', models.Model),
        ),
    ]
