# Generated by Django 5.0.4 on 2024-04-22 01:23

import django.db.models.deletion
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('resources', '0001_initial'),
        ('resource_attrs', '0001_initial'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resource_attrs.resourcecategory', validators=[resources.models.is_resourcecategory_live]),
        ),
        migrations.AddField(
            model_name='resource',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatadatetype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatalanguage'),
        ),
        migrations.AddField(
            model_name='resource',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='resource',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatalicense'),
        ),
        migrations.AddField(
            model_name='resource',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision'),
        ),
    ]
