# Generated by Django 5.0.6 on 2024-06-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name': 'Data Table', 'verbose_name_plural': 'Resources: Data Tables'},
        ),
        migrations.AlterModelOptions(
            name='geometrycollectionvectorlayer',
            options={'verbose_name': 'GeometryCollection Vector Layer', 'verbose_name_plural': 'Resources: GeometryCollection Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='linestringvectorlayer',
            options={'verbose_name': 'LineString Vector Layer', 'verbose_name_plural': 'Resources: LineString Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='multilinestringvectorlayer',
            options={'verbose_name': 'MultiLineString Vector Layer', 'verbose_name_plural': 'Resources: MultiLineString Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='multipointvectorlayer',
            options={'verbose_name': 'MultiPoint Vector Layer', 'verbose_name_plural': 'Resources: MultiPoint Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='multipolygonvectorlayer',
            options={'verbose_name': 'MultiPolygon Vector Layer', 'verbose_name_plural': 'Resources: MultiPolygon Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='polygonvectorlayer',
            options={'verbose_name': 'Polygon Vector Layer', 'verbose_name_plural': 'Resources: Polygon Vector Layers'},
        ),
        migrations.AlterModelOptions(
            name='rasterlayer',
            options={'verbose_name': 'Raster Layer', 'verbose_name_plural': 'Resources: Raster Layers'},
        ),
        migrations.AlterModelOptions(
            name='remotewfs',
            options={'verbose_name': 'WFS Service', 'verbose_name_plural': 'Resources: WFS Services'},
        ),
        migrations.AlterModelOptions(
            name='remotewms',
            options={'verbose_name': 'WMS Service', 'verbose_name_plural': 'Resources: WMS Services'},
        ),
    ]
