# Generated by Django 5.0.4 on 2024-04-22 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0002_initial'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='locked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by'),
        ),
        migrations.AddField(
            model_name='resource',
            name='maintenance_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatamaintenancefrequency'),
        ),
        migrations.AddField(
            model_name='resource',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='regions',
            field=models.ManyToManyField(blank=True, to='metadata.datasetmetadataregion'),
        ),
        migrations.AddField(
            model_name='resource',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatarestrictioncodetype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='spatial_representation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadataspatialrepresentationtype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.datasetmetadatatopiccategory'),
        ),
    ]
